#!/bin/fish

set source "scripts/hooks"

cd (git rev-parse --show-toplevel)

for hook in "$source"/*
	set hook_basename (basename $hook)
	echo "Configuring hook "$hook_basename"."
	ln -srf "$hook" ".git/hooks/$hook_basename"
end
